Add docker
Dmitrii-Petrov/java-shareit pull request #7
Opened 2023-07-08 14:33 UTC by Dmitrii-Petrov

2023-07-08 20:23 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/item/ItemClient.java
> +    public ItemClient(@Value("${shareit-server.url}") String serverUrl, RestTemplateBuilder builder) {
просто совет на будущее - лучше всегда делать свой бин с RestTemplate, чтобы можно было легко настроить, подебажить Я в пути!

2023-07-08 20:30 UTC, db-exp requested changes

2023-07-08 20:30 UTC, db-exp commented on gateway/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotBlank
тоже можно Size добавить

2023-07-08 20:30 UTC, db-exp commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://localhost:9090
лучше взять переменную среды из docker-compose через ${имя_переменной}

2023-07-08 20:30 UTC, db-exp commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
тут тоже и для url и для логин/пароля лучше брать переменные среды

2023-07-08 22:35 UTC, Dmitrii-Petrov commented on gateway/src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotBlank
done

2023-07-08 22:35 UTC, Dmitrii-Petrov commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://localhost:9090
#локально и на гите не запускается, если прописать #shareit-server.url=${SHAREIT_SERVER_URL}

2023-07-08 22:45 UTC, Dmitrii-Petrov commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
#на гите не запускается, если прописать
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${POSTGRES_USER}
#spring.datasource.password=${POSTGRES_PASSWORD}

2023-07-09 08:42 UTC, db-exp approved these changes

2023-07-10 06:19 UTC, merged